# Generated by Django 3.2.8 on 2022-04-11 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='hw_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hw_class1', to='hwapp.class'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='hw_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='overdue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
