# Generated by Django 3.1.7 on 2021-04-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
