# Generated by Django 3.1.7 on 2021-05-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0002_auto_20210428_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='carrier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
