# Generated by Django 3.2.8 on 2022-04-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0002_auto_20220410_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='notion_migrated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
