# Generated by Django 3.1.7 on 2021-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0002_auto_20210419_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='time_def',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
