# Generated by Django 3.0.10 on 2021-06-29 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0002_auto_20210629_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_application', models.CharField(max_length=128)),
                ('link', models.TextField()),
                ('link_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
