# Generated by Django 3.1.7 on 2021-05-29 20:32

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0003_auto_20210528_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default=None, help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
    ]
