# Generated by Django 3.1.7 on 2021-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0003_recurrence_time_def'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrence',
            name='time_def',
        ),
        migrations.AddField(
            model_name='recurrence',
            name='hour_definition',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
