# Generated by Django 3.2.8 on 2022-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0003_homework_notion_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='notion_id',
            field=models.CharField(blank=True, default=False, max_length=256, null=True),
        ),
    ]
