# Generated by Django 3.0.10 on 2021-07-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0003_icslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='ics_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
