# Generated by Django 3.0.10 on 2021-07-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0004_homework_ics_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='ics_uid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
