# Generated by Django 3.1.7 on 2021-04-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0004_auto_20210419_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='hw_title',
            field=models.CharField(max_length=256),
        ),
    ]
