# Generated by Django 3.1.7 on 2021-04-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0005_auto_20210419_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
