# Generated by Django 3.1.7 on 2021-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0005_auto_20210529_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='text_notifications',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
