# Generated by Django 3.0.10 on 2021-07-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0005_auto_20210717_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='ics_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
