# Generated by Django 3.1.7 on 2021-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0006_homework_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
