# Generated by Django 3.1.7 on 2021-06-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0006_preferences_text_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='text_notifications',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
