# Generated by Django 3.0.10 on 2021-07-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0006_class_ics_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='ics_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
