# Generated by Django 3.1.7 on 2021-04-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0007_homework_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='hw_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_class1', to='hwapp.class'),
        ),
    ]
