# Generated by Django 3.2.8 on 2023-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0007_class_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
