# Generated by Django 3.0.10 on 2021-09-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0007_auto_20210721_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
