# Generated by Django 3.1.7 on 2021-06-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0007_auto_20210602_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='calendar_output',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
