# Generated by Django 3.0.10 on 2021-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0008_homework_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='utc_def',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
