# Generated by Django 3.1.7 on 2021-04-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0008_auto_20210422_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='email_recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='hwapp.recurrence'),
        ),
    ]
