# Generated by Django 3.1.7 on 2021-06-05 03:28

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0008_preferences_calendar_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='calendar_output',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='email_notifications',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='text_notifications',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
