# Generated by Django 3.2.8 on 2023-01-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0008_alter_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='external_src',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
