# Generated by Django 3.1.7 on 2021-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0009_auto_20210423_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='active',
        ),
        migrations.AddField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
