# Generated by Django 3.1.7 on 2021-06-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0009_auto_20210604_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='calendar_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='text_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
