# Generated by Django 3.0.10 on 2021-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0009_timezone_utc_def'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='utc_def',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
