# Generated by Django 3.2.8 on 2023-01-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0009_auto_20230110_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='external_id',
            field=models.CharField(blank=True, default=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='external_src',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
