# Generated by Django 3.2.8 on 2023-01-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0010_auto_20230110_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(default=False, max_length=64, null=True),
        ),
    ]
