# Generated by Django 3.0.10 on 2021-09-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0010_auto_20210904_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='calendar_output',
            field=models.BooleanField(default=True),
        ),
    ]
