# Generated by Django 3.2.4 on 2021-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0010_auto_20210604_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='timezone',
            field=models.CharField(default='US/Pacific', max_length=256),
        ),
        migrations.AlterField(
            model_name='class',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='hwapp.Day'),
        ),
        migrations.AlterField(
            model_name='class',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
