# Generated by Django 3.2.4 on 2021-06-18 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0011_auto_20210618_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='timezone',
        ),
        migrations.AddField(
            model_name='preferences',
            name='user_timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.timezone'),
        ),
    ]
