# Generated by Django 3.0.10 on 2021-09-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0011_auto_20210904_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
