# Generated by Django 3.2.8 on 2023-01-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0012_emailtemplate_vestion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='vestion_id',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='version_id',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
