# Generated by Django 3.0.10 on 2021-09-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0012_auto_20210905_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='utc_def',
        ),
    ]
