# Generated by Django 3.2.4 on 2021-06-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0012_auto_20210618_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
