# Generated by Django 3.2.4 on 2021-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0013_alter_homework_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
