# Generated by Django 3.0.10 on 2021-09-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0013_remove_timezone_utc_def'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrence',
            name='hour_definition',
        ),
    ]
