# Generated by Django 3.2.8 on 2023-01-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0013_auto_20230128_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='email_recurrence',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='text_notifications',
        ),
    ]
