# Generated by Django 3.2.4 on 2021-06-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0014_alter_preferences_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
