# Generated by Django 3.2.8 on 2023-01-29 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0014_auto_20230128_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_title', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('days', models.ManyToManyField(to='hwapp.Day')),
                ('hw_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.recurring'),
        ),
    ]
