# Generated by Django 3.2.4 on 2021-06-24 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0015_alter_homework_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_val', models.CharField(max_length=256)),
                ('expires', models.IntegerField()),
                ('reset_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_reset_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
