# Generated by Django 3.2.8 on 2023-01-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0015_auto_20230128_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
