# Generated by Django 3.0.10 on 2021-09-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0015_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Group',
        ),
    ]
