# Generated by Django 3.2.4 on 2021-06-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0016_pwreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwreset',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
