# Generated by Django 3.2.8 on 2023-01-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0016_recurring_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurrence',
        ),
    ]
