# Generated by Django 3.2.4 on 2021-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0017_alter_pwreset_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwreset',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
