# Generated by Django 3.2.8 on 2023-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0017_delete_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='abbreviation',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
