# Generated by Django 3.0.10 on 2021-10-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0017_icshashval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IcsHashVal',
        ),
    ]
