# Generated by Django 3.2.8 on 2021-10-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0018_delete_icshashval'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=64)),
                ('template_body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
