# Generated by Django 3.2.8 on 2023-03-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0018_day_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
