# Generated by Django 3.2.8 on 2021-10-09 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0019_auto_20211008_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcsId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icsID', models.CharField(max_length=512)),
                ('icsID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icsID_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
