# Generated by Django 3.2.13 on 2023-06-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0019_homework_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='calendar_output',
        ),
    ]
