# Generated by Django 3.2.8 on 2021-10-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0020_icsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='ics_uid',
        ),
    ]
