# Generated by Django 3.2.13 on 2023-07-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0001_initial'),
        ('hwapp', '0020_remove_preferences_calendar_output'),

    ]

    operations = [
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='days',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='hw_class',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='user',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='recurring',
        ),
        migrations.DeleteModel(
            name='PWReset',
        ),
        migrations.DeleteModel(
            name='Recurring',
        ),
    ]
