# Generated by Django 3.2.8 on 2021-10-17 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0021_remove_homework_ics_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='days',
        ),
    ]
