# Generated by Django 3.2.13 on 2023-08-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0021_auto_20230710_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allauth',
            options={'verbose_name': 'Auth0 SSO', 'verbose_name_plural': 'Auth0 SSO'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name': 'Preferences', 'verbose_name_plural': 'Preferences'},
        ),
    ]
