# Generated by Django 4.2.7 on 2023-12-17 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hwapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0023_pastebin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hwapp.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
