# Generated by Django 4.2.7 on 2023-12-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0025_filebin_hash_val'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.RemoveField(
            model_name='icslink',
            name='link_user',
        ),
        migrations.AlterModelOptions(
            name='allauth',
            options={'verbose_name': 'SSO Credential', 'verbose_name_plural': 'SSO Credentials'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Site Template', 'verbose_name_plural': 'Site Templates'},
        ),
        migrations.DeleteModel(
            name='IcsId',
        ),
        migrations.DeleteModel(
            name='IcsLink',
        ),
    ]
