# Generated by Django 4.2.7 on 2024-01-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0026_delete_day_remove_icslink_link_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(to='hwapp.emailtemplate'),
        ),
    ]
