# Generated by Django 3.2.13 on 2023-09-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyauth',
            name='access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyauth',
            name='refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('uri', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.spotifyauth')),
            ],
        ),
    ]
