# Generated by Django 3.2.13 on 2023-09-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20230901_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyauth',
            name='s_user_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
