# Generated by Django 3.2.13 on 2023-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_spotifyauth_s_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
