# Generated by Django 3.2.13 on 2023-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_spotifyplaylist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
