# Generated by Django 3.2.8 on 2022-04-11 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwapp', '0002_auto_20220410_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NotionData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('bot_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workspace_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workspace_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('notion_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('bot_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workspace_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workspace_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('db_id', models.TextField(blank=True, default=None, null=True)),
                ('notion_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IcsHashVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_val', models.CharField(max_length=128)),
                ('hash_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ics', models.TextField(blank=True, null=True)),
                ('calendar_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('homework_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.homework')),
                ('integration_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.integrationoption')),
            ],
        ),
        migrations.CreateModel(
            name='AdminOnly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('admin_cookie', models.TextField(default=None)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
