# Generated by Django 3.2.8 on 2022-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notiondata',
            name='db_id',
        ),
        migrations.DeleteModel(
            name='NotionData1',
        ),
    ]
