# Generated by Django 3.2.8 on 2022-04-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20220410_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiondata',
            name='db_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
