# Generated by Django 3.2.4 on 2021-06-25 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoology_ics_link', models.CharField(blank=True, max_length=512, null=True)),
                ('schoology_ics', models.TextField(blank=True, null=True)),
                ('integration_choices', models.ManyToManyField(blank=True, null=True, to='integrations.IntegrationOption')),
                ('integrations_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ics', models.TextField(blank=True, null=True)),
                ('calendar_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('homework_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.homework')),
                ('integration_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.integrationoption')),
            ],
        ),
    ]
