# Generated by Django 3.2.8 on 2022-04-11 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwapp', '0002_auto_20220410_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('bot_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workspace_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workspace_id', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('db_id', models.TextField(blank=True, default=None, null=True)),
                ('notion_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
