# Generated by Django 3.1.7 on 2021-06-01 21:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integration_Preference',
            new_name='IntegrationPreference',
        ),
    ]
