# Generated by Django 3.2.4 on 2021-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationpreference',
            name='admin_link',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
