# Generated by Django 3.2.4 on 2021-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationpreference_admin_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationpreference',
            name='admin_link',
        ),
        migrations.AddField(
            model_name='integrationpreference',
            name='admin_cookie',
            field=models.TextField(default=None),
        ),
    ]
