# Generated by Django 3.1.7 on 2021-06-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20210601_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntegrationOptions',
            new_name='IntegrationOption',
        ),
    ]
