# Generated by Django 3.2.8 on 2022-04-21 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0004_homework_notion_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_adminonly_calendarevent_googledata_icshashval_integrationoption'),
    ]

    operations = [

        migrations.AddField(
            model_name='googledata',
            name='sync_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),

    ]
