# Generated by Django 3.2.4 on 2021-06-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20210625_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegrationPreference',
        ),
    ]
