# Generated by Django 3.1.7 on 2021-06-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20210601_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationoption',
            old_name='integrations',
            new_name='integration',
        ),
    ]
