# Generated by Django 3.0.10 on 2021-06-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_delete_integrationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminonly',
            name='application',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
