# Generated by Django 3.2.8 on 2022-04-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0004_homework_notion_id'),
        ('integrations', '0003_auto_20220421_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googledata',
            old_name='sync_token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='googledata',
            name='id_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='googledata',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
