# Generated by Django 3.2.8 on 2022-04-21 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0004_homework_notion_id'),
        ('integrations', '0004_auto_20220421_1216'),
    ]

    operations = [

        migrations.AddField(
            model_name='googledata',
            name='sync_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),

        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('calendar_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('google_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

    ]
