# Generated by Django 3.0.10 on 2021-09-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_adminonly_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdioticClass',
        ),
    ]
