# Generated by Django 3.1.7 on 2021-06-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20210601_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationpreference',
            name='integration_choices',
            field=models.ManyToManyField(blank=True, null=True, to='integrations.IntegrationOption'),
        ),
    ]
