# Generated by Django 3.2.8 on 2022-04-21 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0004_homework_notion_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0005_auto_20220421_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='GoogleCalendar',
        ),
    ]
