# Generated by Django 3.0.10 on 2021-10-08 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0005_delete_idioticclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcsHashVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_val', models.CharField(max_length=128)),
                ('hash_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
