# Generated by Django 3.1.7 on 2021-06-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20210601_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationpreference',
            name='schoology_ics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationpreference',
            name='schoology_ics_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
