# Generated by Django 3.2.8 on 2022-04-22 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0004_homework_notion_id'),
        ('integrations', '0006_auto_20220421_1627'),
    ]

    operations = [

        migrations.AddField(
            model_name='googlecalendar',
            name='sync_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
