# Generated by Django 3.2.8 on 2023-01-11 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0007_class_archived'),
        ('integrations', '0007_auto_20220422_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoologyClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(blank=True, default=None, null=True)),
                ('s_class_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('s_grading_period', models.IntegerField(blank=True, default=None, null=True)),
                ('schoology_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoologyAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_consumer_key', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('s_secret_key', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('h_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

    ]
