# Generated by Django 3.1.7 on 2021-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
