# Generated by Django 3.1.7 on 2021-06-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_calendarevent_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='completed',
        ),
    ]
