# Generated by Django 3.2.8 on 2023-01-11 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0008_alter_class_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0008_calendarevent_icshashval_schoologyauth_schoologyclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoologyclasses',
            name='update',
            field=models.BooleanField(blank=True, null=True),
        ),

    ]
