# Generated by Django 3.1.7 on 2021-06-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_remove_calendarevent_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='ics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
