# Generated by Django 3.2.8 on 2023-01-11 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0010_auto_20230110_2152'),
        ('integrations', '0009_auto_20230110_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoologyclasses',
            name='linked_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.class'),
        ),
    ]
