# Generated by Django 3.1.7 on 2021-06-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_auto_20210602_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='schoology_ics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
