# Generated by Django 3.2.8 on 2023-01-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0010_auto_20230110_2152'),
        ('integrations', '0010_auto_20230110_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoologyauth',
            name='src',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='schoologyclasses',
            name='src',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
