# Generated by Django 3.1.7 on 2021-06-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0010_auto_20210604_2030'),
        ('integrations', '0011_calendarevent_schoology_ics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='schoology_ics',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='homework_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.homework'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='integration_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.integrationoption'),
        ),
    ]
