# Generated by Django 3.2.8 on 2023-01-13 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0010_auto_20230110_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0013_auto_20230111_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoologyclasses',
            name='auth_data',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.schoologyauth'),
        ),

    ]
