# Generated by Django 3.2.13 on 2023-06-15 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0020_remove_preferences_calendar_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0017_calendarevent_icshashval_integrationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationlog',
            name='dest',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),

    ]
