# Generated by Django 3.2.13 on 2023-07-06 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0020_remove_preferences_calendar_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0019_auto_20230616_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlog',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=100000, null=True),
        ),
    ]
