# Generated by Django 3.2.13 on 2023-07-10 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwapp', '0021_auto_20230710_1035'),
        ('integrations', '0020_auto_20230705_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlog',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
