# Generated by Django 3.2.13 on 2023-08-05 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0022_auto_20230804_1856'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0022_calendarevent_icshashval_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.CharField(blank=0, default=0, max_length=16, null=0),
        ),
    ]
