# Generated by Django 3.2.13 on 2023-08-14 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0022_auto_20230804_1856'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0023_auto_20230804_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiondata',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
