# Generated by Django 4.2.8 on 2025-01-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0027_user_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0025_icshashval_remove_googledata_google_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradescopeCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradescopeClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(blank=True, default=None, null=True)),
                ('class_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('linked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwapp.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
